/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sudoku;

public class Sudoku {

    public static void main(String[] args) {
    }
    public static int[][] getExample(){
        return null;
    }
}
