/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sudoku;

import org.junit.Test;
import static org.junit.Assert.*;

public class SudokuTest {
    @Test public void appHasAGreeting() {
        Sudoku classUnderTest = new Sudoku();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
