/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Praktikum_4;

import Praktikum_4.gamblinghall.DoubleShot;

public class App {

    public static void main(String[] args) {
    var doubleshot1 = new DoubleShot("double shot 1");
    var doubleshot2 = new DoubleShot("double shot 2");
    var doubleshot3 = new DoubleShot("double shot 3");
    for(int i=0;i<100000;i++){
        doubleshot1.play(100);
        doubleshot2.play(100);
        doubleshot3.play(100);
    }
    }
}
